site_name: brainchop
site_url: https://neuroneural.github.io/brainchop-cli/
repo_url: https://github.com/neuroneural/brainchop-cli

nav:
  - Home: index.md
  - API Reference: api.md

theme:
  name: mkdocs

plugins:
  - search
  - mkdocstrings
